### ISSUE TITLE
Errors in manual

### ISSUE THREAD

**Issue by lksrmp** [cp-paw/cp-paw#11]
- [x] names with underscore are not searchable e.g. paw_strc, maybe use `\usepackage[T1]{fontenc}`
- [x] broken reference in _6.2.31 !CONTROL!ANALYSE!1DPOT_
- [x] broken reference in _17.4.1 !STRC!ATOM:FFTYPE_
- [x] should default value for `!CONTROL!ANALYSE!1DPOT:IT` be a vector?
- [x] `!STRUCTURE!SPECIES!AUGMENT:RBOX/RCOV` entry not completed
- [x] should default value of `!CONTROL!GENERIC:DT` be 5.0?

**Comment by pbloechl** [comment]
\usepackage[T1]{fontenc} is included I find underscores searchable on my mac.
!CONTROL!GENERIC:DT=5.0 is correct
