### ISSUE TITLE
paw_bands.x illegal instruction on Apple Silicon

### ISSUE THREAD

**Issue by lksrmp** [cp-paw/cp-paw#3]
Running `paw_bands.x` with `MODE='DIAGONALISATION'` on Apple M1Max Processor causes the error below. However, the job is not being terminated. Files for a minimal example for silicon: [Silicon.zip](https://github.com/cp-paw/cp-paw/files/9475899/Silicon.zip)

The error seems to occur during the calling of a LAPACK routine.

>  CNTLNAMEsi_1.bcntl          10           0
> TRACE-PUSH(  1): LEVEL=    1 INTO MAIN
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.979
> TRACE-PUSH(  1): LEVEL=    2 INTO STANDARDFILES_BANDS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.980
> TRACE-POP (  1): LEVEL=    2 FROM STANDARDFILES_BANDS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.980
> TRACE-PUSH(  1): LEVEL=    2 INTO BANDS_BANDSTRUCTURE_DIAG
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-PUSH(  1): LEVEL=    3 INTO BANDDATA__READFILE
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-PUSH(  1): LEVEL=    4 INTO BANDDATA_READ
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-POP (  1): LEVEL=    4 FROM BANDDATA_READ
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-POP (  1): LEVEL=    3 FROM BANDDATA__READFILE
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
>  EPW FROM INPUT=   15.000000000000000
>  EPW MODIFIED FOR PROPER CUTOFF=   28.182781322615991
> TRACE-PUSH(  1): LEVEL=    3 INTO PLANEWAVE__INITIALIZE
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-PUSH(  1): LEVEL=    4 INTO PLANEWAVE_MAPSTRIPESTOTASKS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-POP (  1): LEVEL=    4 FROM PLANEWAVE_MAPSTRIPESTOTASKS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.981
> TRACE-POP (  1): LEVEL=    3 FROM PLANEWAVE__INITIALIZE
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.982
>  EPW2 NG   28.182781322615991             1917
> TRACE-PUSH(  1): LEVEL=    3 INTO COMPUTE K-INDEPENDENT ARRAYS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093218.999
>  LIB_FFTW: CREATE PLAN FOR: GTOR           1          18           0
>  LIB_FFTW: CREATE PLAN FOR: RTOG          -1          18           1
> TRACE-POP (  1): LEVEL=    3 FROM COMPUTE K-INDEPENDENT ARRAYS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093219.261
>  +++++++++++++++++ SPIN=           1 ++++++++++++++++++
> TRACE-PASS(  1): LEVEL=  2 WHERE:AFTER READ BNCTL
> TRACE-PUSH(  1): LEVEL=    3 INTO ITERATE KPOINTS
> TRACE-MEM(  1): MAXMEM[MBYTE]=   0.00000 TIME20220902 093219.261
>  DIMENSION OF THE RAW POTENTIAL MATRIX        1917
>  DIMENSION OF EIGENPROBLEM         749
> 
> Program received signal SIGILL: Illegal instruction.
> 
> Backtrace for this error:
> 
> Program received signal SIGTRAP: Trace/breakpoint trap.
> 
> Backtrace for this error:

**Comment by pbloechl** [comment]
Problem ist fixed
